@dog(name:str, age:int) {
    #bark:void(){
        this.age = 10;
        print(name);
    }
    #getage:int(){
        <- this.age;
    }
}

#factorial:int(number:int) {
    $res:int;
    if (number < 2) {
        res = 1;
    } else {
        res = number * factorial(number-1);
    }
    <- res;
}

$fito:dog = new dog('fito', 3);
fito.bark();
print(fito.getage());

$foo:stack(int);

print('Ingrese limite para buscar factorial.');
$limit:int = read();
$i:int = 1;
while (i < limit) {
    foo.push( factorial(i) );
    i = i + 1;
}

$j:int = foo.size();
while (j > 0) {
    print(foo.pop());
    j = foo.size();
}