#!/usr/bin/python

import os
import sys
import grammar
from virtualmachine.WitzVirtualMachine import WitzVirtualMachine

if len(sys.argv) > 1:
	filename = sys.argv[1]
	witz_file = open(filename, 'r')
	try:
		fn = os.path.splitext(filename)[0] + '.wz'
		grammar.target_file = fn
		grammar.parser.parse(witz_file.read())
		quads_file = open(fn, 'r')
		vm = WitzVirtualMachine(quads_file)
		vm.run()
		quads_file.close()
	except Exception as e:
		print e
	witz_file.close()
else:
	print('Falta nombre de archivo .wit')