@dog(name:str, age:int){

}

$fito:dog = new dog("fito", 3);
print(fito.name);
fito.name = "el nombre nuevo de fito";
print(fito.name);
$lalo:dog = fito;
lalo.name = "lalo";
print(lalo.name);
print(fito.name);